apiVersion: apps/v1
kind: Deployment
metadata:
  name: funathon-2026-project3-model-deployment
spec:
  replicas: 25
  selector:
    matchLabels:
      app: funathon-2026-project3-model-deployment
  template:
    metadata:
      labels:
        app: funathon-2026-project3-model-deployment
    spec:
      containers:
        - name: funathon-2026-project3-app
          image: rayaberova/hackathon-ntts-2025:main
          imagePullPolicy: Always
          env:
            # env var for s3 connexion
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mc-s3
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mc-s3
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr
            - name: MLFLOW_S3_ENDPOINT_URL
              value: https://minio.lab.sspcloud.fr
            - name: MLFLOW_TRACKING_URI
              value: projet-formation-mlflow.user.lab.sspcloud.fr
            - name: MLFLOW_TRACKING_USERNAME
              value: projet-formation
            - name: MLFLOW_TRACKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow
                  key: password
            - name: MLFLOW_MODEL_NAME
              value: segmentation-sentinel2-model
            - name: MLFLOW_MODEL_VERSION
              value: "2"
            - name: MLFLOW_ENABLE_ARTIFACTS_PROGRESS_BAR
              value: "false"
          resources:
            limits:
              memory: "75Gi"
              cpu: "100000m"
            requests:
              memory: "8Gi"
              cpu: "1000m"