apiVersion: v1
kind: Service
metadata:
  name: funathon-2026-project3-model-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: funathon-2026-project3-model-deployment