apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: predict-nuts-
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: regions
        value: '[{"nuts": "AT332", "year": 2018}, {"nuts": "AT332", "year": 2021}, {"nuts": "AT332", "year": 2024}, {"nuts": "BE100", "year": 2018}, {"nuts": "BE100", "year": 2021}, {"nuts": "BE100", "year": 2024}, {"nuts": "BE251", "year": 2018}, {"nuts": "BE251", "year": 2021}, {"nuts": "BE251", "year": 2024}, {"nuts": "BG322", "year": 2018}, {"nuts": "BG322", "year": 2021}, {"nuts": "BG322", "year": 2024}, {"nuts": "CY000", "year": 2021}, {"nuts": "CY000", "year": 2024}, {"nuts": "CZ072", "year": 2021}, {"nuts": "CZ072", "year": 2024}, {"nuts": "DEA54", "year": 2018}, {"nuts": "DEA54", "year": 2021}, {"nuts": "DEA54", "year": 2024}, {"nuts": "DK041", "year": 2018}, {"nuts": "DK041", "year": 2024}, {"nuts": "EE00A", "year": 2018}, {"nuts": "EE00A", "year": 2021}, {"nuts": "EE00A", "year": 2024}, {"nuts": "EL521", "year": 2018}, {"nuts": "EL521", "year": 2021}, {"nuts": "EL521", "year": 2024}, {"nuts": "ES612", "year": 2018}, {"nuts": "ES612", "year": 2021}, {"nuts": "ES612", "year": 2024}, {"nuts": "FI1C1", "year": 2018}, {"nuts": "FI1C1", "year": 2021}, {"nuts": "FI1C1", "year": 2024}, {"nuts": "FRJ27", "year": 2018}, {"nuts": "FRJ27", "year": 2021}, {"nuts": "FRJ27", "year": 2024}, {"nuts": "FRK26", "year": 2018}, {"nuts": "FRK26", "year": 2021}, {"nuts": "FRK26", "year": 2024}, {"nuts": "HR050", "year": 2018}, {"nuts": "HR050", "year": 2021}, {"nuts": "HR050", "year": 2024}, {"nuts": "IE061", "year": 2018}, {"nuts": "IE061", "year": 2021}, {"nuts": "ITI32", "year": 2018}, {"nuts": "ITI32", "year": 2021}, {"nuts": "ITI32", "year": 2024}, {"nuts": "LT028", "year": 2018}, {"nuts": "LT028", "year": 2021}, {"nuts": "LT028", "year": 2024}, {"nuts": "LU000", "year": 2018}, {"nuts": "LU000", "year": 2021}, {"nuts": "LU000", "year": 2024}, {"nuts": "LV008", "year": 2018}, {"nuts": "LV008", "year": 2021}, {"nuts": "LV008", "year": 2024}, {"nuts": "MT001", "year": 2018}, {"nuts": "MT001", "year": 2021}, {"nuts": "MT001", "year": 2024}, {"nuts": "NL33C", "year": 2018}, {"nuts": "NL33C", "year": 2021}, {"nuts": "NL33C", "year": 2024}, {"nuts": "PL414", "year": 2018}, {"nuts": "PL414", "year": 2021}, {"nuts": "PL414", "year": 2024}, {"nuts": "PT16I", "year": 2018}, {"nuts": "PT16I", "year": 2021}, {"nuts": "PT16I", "year": 2024}, {"nuts": "RO123", "year": 2018}, {"nuts": "RO123", "year": 2021}, {"nuts": "RO123", "year": 2024}, {"nuts": "SE311", "year": 2018}, {"nuts": "SE311", "year": 2021}, {"nuts": "SE311", "year": 2024}, {"nuts": "SI035", "year": 2018}, {"nuts": "SI035", "year": 2021}, {"nuts": "SI035", "year": 2024}, {"nuts": "SK022", "year": 2018}, {"nuts": "SK022", "year": 2021}, {"nuts": "SK022", "year": 2024}, {"nuts": "UKJ22", "year": 2018}, {"nuts": "UKJ22", "year": 2021}, {"nuts": "UKJ22", "year": 2024}, {"nuts": "UKRAINE", "year": 2018}, {"nuts": "UKRAINE", "year": 2021}, {"nuts": "UKRAINE", "year": 2024}]'

  templates:
    - name: main
      dag:
        tasks:
          - name: run-predict
            template: run-predict-task
            arguments:
              parameters:
                - name: nuts
                  value: "{{item.nuts}}"
                - name: year
                  value: "{{item.year}}"
            withParam: "{{workflow.parameters.regions}}"

    - name: run-predict-task
      inputs:
        parameters:
          - name: nuts
          - name: year
      container:
        image:  rayaberova/hackathon-ntts-2025:main
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: [
           "git clone https://github.com/InseeFrLab/hackathon-ntts-2025.git &&
           cd /api/hackathon-ntts-2025/inference/ &&
           python main.py --nuts3 {{inputs.parameters.nuts}} --year {{inputs.parameters.year}}"
        ]
        env:
          - name: PROJ_LIB
            value: /opt/conda/share/proj
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mc-s3
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mc-s3
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
